#!/bin/bash

# Copia nosso arquivo de configuração personalizado do Nginx para o local correto
cp /home/site/wwwroot/default /etc/nginx/sites-available/default

# Reinicia o Nginx para que as alterações tenham efeito
service nginx restart

# ======= NOSSA SOLUÇÃO =======
# Navega para a pasta do projeto e roda os comandos do Laravel
# durante a inicialização do servidor.

cd /home/site/wwwroot

php artisan key:generate --force
php artisan config:cache
php artisan migrate --force

# =============================